import { useState, useEffect } from 'react';
import Navbar from '../components/Navbar';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Truck, Phone, Scan, User, Droplets, Bell, Globe, Wifi, WifiOff,
  Landmark, HeartPulse, Activity, ChevronRight, CheckCircle2,
  Calendar, AlertTriangle, Shield, Zap
} from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';
import { useAuth } from '../context/AuthContext';

// Local translations for all 6 languages supported by the platform
const base64Translations = "eyJlbiI6IHsic3VidGl0bGUiOiAiV2UgYXJlIGhlcmUgdG8gc3VwcG9ydCB5b3VyIGhlYWx0aCBhbmQgd2VsbC1iZWluZy4iLCAib2ZmbGluZU1vZGUiOiAiT2ZmbGluZSBNb2RlIiwgIm9ubGluZU1vZGUiOiAiQ29ubmVjdGVkIHRvIEFXUyIsICJlbWVyZ2VuY3lIZWxwIjogIkVtZXJnZW5jeSBIZWxwIiwgImVtZXJnZW5jeURlc2MiOiAiTmVlZCBpbW1lZGlhdGUgbWVkaWNhbCBoZWxwPyBDYWxsIGFtYnVsYW5jZSBvciBhbGVydCBBU0hBIHdvcmtlci4iLCAiY2FsbEhlbHBCdG4iOiAiQ2FsbCBmb3IgSGVscCBOb3ciLCAiaGVhbHRoQWxlcnQiOiAiVmlsbGFnZSBIZWFsdGggQWxlcnQiLCAibmV3QmFkZ2UiOiAiTmV3IiwgImFsZXJ0RGVzYyI6ICJGZXZlciBjYXNlcyBhcmUgaW5jcmVhc2luZyBpbiB5b3VyIGFyZWEuIERyaW5rIGNsZWFuIHdhdGVyIGFuZCBzdGF5IHNhZmUuIiwgInZpZXdEZXRhaWxzIjogIlZpZXcgRGV0YWlscyIsICJhbGVydE1vZGFsVGl0bGUiOiAiVmlsbGFnZSBIZWFsdGggQWxlcnQgRGV0YWlscyIsICJhbGVydExvY2F0aW9uIjogIkxvY2F0aW9uOiBWYXJhbmFzaSBEaXN0cmljdCAoWW91ciBWaWxsYWdlKSIsICJhbGVydFN0YXR1cyI6ICJTdGF0dXM6IEFjdGl2ZSBBZHZpc29yeSIsICJhbGVydFByZWNhdXRpb24xIjogIkJvaWwgRHJpbmtpbmcgV2F0ZXI6IEZpbHRlciBhbmQgYm9pbCBhbGwgd2F0ZXIgdG8gcHJldmVudCB3YXRlcmJvcm5lIGluZmVjdGlvbnMuIiwgImFsZXJ0UHJlY2F1dGlvbjIiOiAiVXNlIE1vc3F1aXRvIE5ldHM6IFNsZWVwIHVuZGVyIGluc2VjdCBuZXRzIHRvIHByb3RlY3QgYWdhaW5zdCB2ZWN0b3ItYm9ybmUgdHJhbnNtaXNzaW9uLiIsICJhbGVydFByZWNhdXRpb24zIjogIkFTSEEgQ29udGFjdDogUmVwb3J0IGhpZ2ggZmV2ZXJzIGltbWVkaWF0ZWx5IHRvIEFTSEEgd29ya2VycyBmb3IgZWFybHkgdHJlYXRtZW50LiIsICJjYWxsQXNoYSI6ICJDYWxsIEFTSEEgV29ya2VyIiwgImNsb3NlQnRuIjogIkNsb3NlIiwgIm15SGVhbHRoU2VydmljZXMiOiAiTXkgSGVhbHRoIFNlcnZpY2VzIiwgImNoZWNrU3ltcHRvbXMiOiAiQ2hlY2sgU3ltcHRvbXMiLCAiY2hlY2tTeW1wdG9tc0Rlc2MiOiAiQ2hlY2sgeW91ciBzeW1wdG9tcyBhbmQgZ2V0IHN1Z2dlc3Rpb25zLiIsICJteVJlY29yZHMiOiAiTXkgSGVhbHRoIFJlY29yZHMiLCAibXlSZWNvcmRzRGVzYyI6ICJWaWV3IHlvdXIgaGVhbHRoIHJlY29yZHMgYW5kIHBhc3QgY2hlY2t1cHMuIiwgIndvbWVuUHJlZ25hbmN5IjogIldvbWVuICYgUHJlZ25hbmN5IiwgIndvbWVuUHJlZ25hbmN5RGVzYyI6ICJQcmVnbmFuY3kgY2FyZSwgdHJhY2tpbmcgYW5kIHN1cHBvcnQuIiwgImdvdlNjaGVtZXMiOiAiR292ZXJubWVudCBTY2hlbWVzIiwgImdvdlNjaGVtZXNEZXNjIjogIkNoZWNrIHNjaGVtZXMgYW5kIGJlbmVmaXRzIHlvdSBhcmUgZWxpZ2libGUgZm9yLiIsICJoZWFsdGhTbmFwc2hvdCI6ICJZb3VyIEhlYWx0aCBTbmFwc2hvdCIsICJoZWFsdGhTY29yZSI6ICJIZWFsdGggU2NvcmUiLCAiaGVhbHRoU2NvcmVTdGF0dXMiOiAiR29vZCIsICJjaGVja3Vwc0RvbmUiOiAiQ2hlY2t1cHMgRG9uZSIsICJjaGVja3Vwc0RvbmVTdWIiOiAiVGhpcyB5ZWFyIiwgImFjdGl2ZUFsZXJ0cyI6ICJBY3RpdmUgQWxlcnRzIiwgImFjdGl2ZUFsZXJ0c1N1YiI6ICJBY3Rpb24gUmVxdWlyZWQiLCAibGFzdENoZWNrdXAiOiAiTGFzdCBDaGVja3VwIiwgImRheXNBZ28iOiAiMTUgRGF5cyBBZ28iLCAibGFzdENoZWNrdXBEYXRlIjogIjE0IE1heSAyMDI1IiwgInByb29mVGl0bGUxIjogIlplcm8gRW5nbGlzaCBCYXJyaWVyIiwgInByb29mRGVzYzEiOiAiVHlwZSBvciB0YWxrIGluIG5hdGl2ZSBIaW5kaSwgVGFtaWwsIFRlbHVndSwgTWFyYXRoaSwgb3IgQmVuZ2FsaS4iLCAicHJvb2ZUaXRsZTIiOiAiTm8gSW50ZXJuZXQgTmVlZGVkIiwgInByb29mRGVzYzIiOiAiTG9nIHJlY29yZHMgJiBjaGVjayBzeW1wdG9tcyBpbiByZW1vdGUgZmFybSBmaWVsZHM7IHN5bmNzIGxhdGVyLiIsICJwcm9vZlRpdGxlMyI6ICJTZWN1cmUgSGVhbHRoIExvY2tlciIsICJwcm9vZkRlc2MzIjogIkFFUy0yNTYgbWlsaXRhcnktZ3JhZGUgbG9jYWwgZW5jcnlwdGlvbiBwcm90ZWN0cyBwYXRpZW50IHByaXZhY3kuIiwgInByb29mVGl0bGU0IjogIkluc3RhbnQgQUkgVHJpYWdlIiwgInByb29mRGVzYzQiOiAiSW4tYnJvd3NlciBBSSBhbmFseXplcyBzeW1wdG9tcyBpbW1lZGlhdGVseSB3aXRoIHplcm8gbGF0ZW5jeS4ifSwgImhpIjogeyJzdWJ0aXRsZSI6ICLgpLngpK4g4KSv4KS54KS+4KSBIOCkhuCkquCkleClhyDgpLjgpY3gpLXgpL7gpLjgpY3gpKXgpY3gpK8g4KSU4KSwIOCkleCksuCljeCkr+CkvuCkoyDgpJXgpYcg4KSy4KS/4KSPIOCkueCliOCkguClpCIsICJvZmZsaW5lTW9kZSI6ICLgpJHgpKvgpLLgpL7gpIfgpKgg4KSu4KWL4KShIiwgIm9ubGluZU1vZGUiOiAiQVdTIOCkuOClhyDgpJXgpKjgpYfgpJXgpY3gpJ/gpYfgpKEiLCAiZW1lcmdlbmN5SGVscCI6ICLgpIbgpKrgpL7gpKTgpJXgpL7gpLLgpYDgpKgg4KS44KS54KS+4KSv4KSk4KS+IiwgImVtZXJnZW5jeURlc2MiOiAi4KSk4KWB4KSw4KSC4KSkIOCkmuCkv+CkleCkv+CkpOCljeCkuOCkviDgpLjgpLngpL7gpK/gpKTgpL4g4KSa4KS+4KS54KS/4KSPPyDgpI/gpK7gpY3gpKzgpYHgpLLgpYfgpILgpLgg4KSs4KWB4KSy4KS+4KSP4KSCIOCkr+CkviDgpIbgpLbgpL4g4KSV4KS+4KSw4KWN4KSv4KSV4KSw4KWN4KSk4KS+IOCkleCliyDgpLjgpYLgpJrgpL/gpKQg4KSV4KSw4KWH4KSC4KWkIiwgImNhbGxIZWxwQnRuIjogIuCkuOCkueCkvuCkr+CkpOCkviDgpJXgpYcg4KSy4KS/4KSPIOCkleClieCksiDgpJXgpLDgpYfgpIIiLCAiaGVhbHRoQWxlcnQiOiAi4KSX4KWN4KSw4KS+4KSuIOCkuOCljeCkteCkvuCkuOCljeCkpeCljeCkryDgpJrgpYfgpKTgpL7gpLXgpKjgpYAiLCAibmV3QmFkZ2UiOiAi4KSo4KSv4KS+IiwgImFsZXJ0RGVzYyI6ICLgpIbgpKrgpJXgpYcg4KSV4KWN4KS34KWH4KSk4KWN4KSwIOCkruClh+CkgiDgpKzgpYHgpJbgpL7gpLAg4KSV4KWHIOCkruCkvuCkruCksuClhyDgpKzgpKLgpLwg4KSw4KS54KWHIOCkueCliOCkguClpCDgpLjgpL7gpKsg4KSq4KS+4KSo4KWAIOCkquCkv+Ckj+CkgiDgpJTgpLAg4KS44KWB4KSw4KSV4KWN4KS34KS/4KSkIOCksOCkueClh+CkguClpCIsICJ2aWV3RGV0YWlscyI6ICLgpLXgpL/gpLXgpLDgpKMg4KSm4KWH4KSW4KWH4KSCIiwgImFsZXJ0TW9kYWxUaXRsZSI6ICLgpJfgpY3gpLDgpL7gpK4g4KS44KWN4KS14KS+4KS44KWN4KSl4KWN4KSvIOCkmuClh+CkpOCkvuCkteCkqOClgCDgpLXgpL/gpLXgpLDgpKMiLCAiYWxlcnRMb2NhdGlvbiI6ICLgpLjgpY3gpKXgpL7gpKg6IOCkteCkvuCksOCkvuCko+CkuOClgCDgpJzgpL/gpLLgpL4gKOCkhuCkquCkleCkviDgpJfgpL7gpIHgpLUpIiwgImFsZXJ0U3RhdHVzIjogIuCkuOCljeCkpeCkv+CkpOCkvzog4KS44KSV4KWN4KSw4KS/4KSvIOCkuOCljeCkteCkvuCkuOCljeCkpeCljeCkryDgpLjgpLLgpL7gpLkiLCAiYWxlcnRQcmVjYXV0aW9uMSI6ICLgpKrgpYDgpKjgpYcg4KSV4KS+IOCkquCkvuCkqOClgCDgpIngpKzgpL7gpLLgpYfgpII6IOCknOCksuCknOCkqOCkv+CkpCDgpLjgpILgpJXgpY3gpLDgpK7gpKMg4KS44KWHIOCkrOCkmuCkqOClhyDgpJXgpYcg4KSy4KS/4KSPIOCkuOCkvuCksOCkviDgpKrgpL7gpKjgpYAg4KSb4KS+4KSo4KWH4KSCIOCklOCksCDgpIngpKzgpL7gpLLgpYfgpILgpaQiLCAiYWxlcnRQcmVjYXV0aW9uMiI6ICLgpK7gpJrgpY3gpJvgpLDgpKbgpL7gpKjgpYAg4KSV4KS+IOCkquCljeCksOCkr+Cli+CklyDgpJXgpLDgpYfgpII6IOCkteClh+CkleCljeCkn+CksC3gpJzgpKjgpL/gpKQg4KS44KSC4KSV4KWN4KSw4KSu4KSjIOCkuOClhyDgpKzgpJrgpKjgpYcg4KSV4KWHIOCksuCkv+CkjyDgpK7gpJrgpY3igI3gpJvgpLDgpKbgpL7gpKjgpYAg4KSu4KWH4KSCIOCkuOCli+Ckj+CkguClpCIsICJhbGVydFByZWNhdXRpb24zIjogIuCkhuCktuCkviDgpLjgpYcg4KS44KSC4KSq4KSw4KWN4KSVIOCkleCksOClh+Ckgjog4KSk4KWB4KSw4KSC4KSkIOCkieCkquCkmuCkvuCksCDgpJXgpYcg4KSy4KS/4KSPIOCkpOClh+CknCDgpKzgpYHgpJbgpL7gpLAg4KSV4KWAIOCkuOClguCkmuCkqOCkviDgpIbgpLbgpL4g4KSV4KS+4KSw4KWN4KSv4KSV4KSw4KWN4KSk4KS+IOCkleCliyDgpKbgpYfgpILgpaQiLCAiY2FsbEFzaGEiOiAi4KSG4KS24KS+IOCkleCkvuCksOCljeCkr+CkleCksOCljeCkpOCkviDgpJXgpYsg4KSV4KWJ4KSyIOCkleCksOClh+CkgiIsICJjbG9zZUJ0biI6ICLgpKzgpILgpKYg4KSV4KSw4KWH4KSCIiwgIm15SGVhbHRoU2VydmljZXMiOiAi4KSu4KWH4KSw4KWAIOCkuOCljeCkteCkvuCkuOCljeCkpeCljeCkryDgpLjgpYfgpLXgpL7gpI/gpIIiLCAiY2hlY2tTeW1wdG9tcyI6ICLgpLLgpJXgpY3gpLfgpKPgpYvgpIIg4KSV4KWAIOCknOCkvuCkguCkmiDgpJXgpLDgpYfgpIIiLCAiY2hlY2tTeW1wdG9tc0Rlc2MiOiAi4KSF4KSq4KSo4KWHIOCksuCkleCljeCkt+Cko+Cli+CkgiDgpJXgpYAg4KSc4KS+4KSC4KSaIOCkleCksOClh+CkgiDgpJTgpLAg4KS44KWB4KSd4KS+4KS1IOCkquCljeCksOCkvuCkquCljeCkpCDgpJXgpLDgpYfgpILgpaQiLCAibXlSZWNvcmRzIjogIuCkruClh+CksOClhyDgpLjgpY3gpLXgpL7gpLjgpY3gpKXgpY3gpK8g4KSw4KS/4KSV4KWJ4KSw4KWN4KShIiwgIm15UmVjb3Jkc0Rlc2MiOiAi4KSF4KSq4KSo4KWHIOCkuOCljeCkteCkvuCkuOCljeCkpeCljeCkryDgpLDgpL/gpJXgpYngpLDgpY3gpKEg4KSU4KSwIOCkquCkv+Ckm+CksuClhyDgpJrgpYfgpJXgpIXgpKog4KSm4KWH4KSW4KWH4KSC4KWkIiwgIndvbWVuUHJlZ25hbmN5IjogIuCkruCkueCkv+CksuCkviDgpJTgpLAg4KSX4KSw4KWN4KSt4KS+4KS14KS44KWN4KSl4KS+IiwgIndvbWVuUHJlZ25hbmN5RGVzYyI6ICLgpJfgpLDgpY3gpK3gpL7gpLXgpLjgpY3gpKXgpL4g4KSV4KWAIOCkpuClh+CkluCkreCkvuCksiwg4KSf4KWN4KSw4KWI4KSV4KS/4KSC4KSXIOCklOCksCDgpLjgpLngpL7gpK/gpKTgpL7gpaQiLCAiZ292U2NoZW1lcyI6ICLgpLjgpLDgpJXgpL7gpLDgpYAg4KSv4KWL4KSc4KSo4KS+4KSP4KSCIiwgImdvdlNjaGVtZXNEZXNjIjogIuCkieCkqCDgpK/gpYvgpJzgpKjgpL7gpJPgpIIg4KSU4KSwIOCksuCkvuCkreCli+CkgiDgpJXgpYAg4KSc4KS+4KSC4KSaIOCkleCksOClh+CkgiDgpJzgpL/gpLjgpJXgpYcg4KSG4KSqIOCkquCkvuCkpOCljeCksCDgpLngpYjgpILgpaQiLCAiaGVhbHRoU25hcHNob3QiOiAi4KSG4KSq4KSV4KS+IOCkuOCljeCkteCkvuCkuOCljeCkpeCljeCkryDgpLjgpL7gpLDgpL7gpILgpLYiLCAiaGVhbHRoU2NvcmUiOiAi4KS44KWN4KS14KS+4KS44KWN4KSl4KWN4KSvIOCkuOCljeCkleCli+CksCIsICJoZWFsdGhTY29yZVN0YXR1cyI6ICLgpIXgpJrgpY3gpJvgpL4iLCAiY2hlY2t1cHNEb25lIjogIuCkmuClh+CkleCkheCkqiDgpKrgpYLgpLDgpYcg4KS54KWB4KSPIiwgImNoZWNrdXBzRG9uZVN1YiI6ICLgpIfgpLgg4KS14KSw4KWN4KS3IiwgImFjdGl2ZUFsZXJ0cyI6ICLgpLjgpJXgpY3gpLDgpL/gpK8g4KSa4KWH4KSk4KS+4KS14KSo4KS/4KSv4KS+4KSCIiwgImFjdGl2ZUFsZXJ0c1N1YiI6ICLgpJXgpL7gpLDgpY3gpLDgpLXgpL7gpIgg4KSG4KS14KS24KWN4KSv4KSVIiwgImxhc3RDaGVja3VwIjogIuCkheCkguCkpOCkv+CkriDgpJrgpYfgpJXgpIXgpKoiLCAiZGF5c0FnbyI6ICIxNSDgpKbgpL/gpKgg4KSq4KS54KSy4KWHIiwgImxhc3RDaGVja3VwRGF0ZSI6ICIxNCDgpK7gpIggMjAyNSIsICJwcm9vZlRpdGxlMSI6ICLgpK3gpL7gpLfgpL4g4KSV4KWAIOCkleCli+CkiCDgpKzgpL7gpKfgpL4g4KSo4KS54KWA4KSCIiwgInByb29mRGVzYzEiOiAi4KSF4KSq4KSo4KWAIOCkruCkvuCkpOClg+CkreCkvuCkt+CkviAo4KS54KS/4KSC4KSm4KWALCDgpKTgpK7gpL/gpLIsIOCkpOClh+CksuClgeCkl+ClgSwg4KSu4KSw4KS+4KSg4KWALCDgpKzgpILgpJfgpL7gpLLgpYApIOCkruClh+CkgiDgpKzgpYvgpLLgpYfgpIIg4KSv4KS+IOCksuCkv+CkluClh+CkguClpCIsICJwcm9vZlRpdGxlMiI6ICLgpKzgpL/gpKjgpL4g4KSH4KSC4KSf4KSw4KSo4KWH4KSfIOCkleClhyDgpJXgpL7gpK4iLCAicHJvb2ZEZXNjMiI6ICLgpKbgpYLgpLDgpKbgpLDgpL7gpJwg4KSV4KWHIOCkluClh+CkpOCli+CkgiDgpK7gpYfgpIIg4KSt4KWAIOCknOCkvuCkguCkmiDgpJXgpLDgpYfgpII7IOCkqOClh+Ckn+CkteCksOCljeCklSDgpIbgpKjgpYcg4KSq4KSwIOCkluClgeCkpiDgpLjgpL/gpILgpJUg4KS54KWL4KSX4KS+4KWkIiwgInByb29mVGl0bGUzIjogIuCkuOClgeCksOCkleCljeCkt+Ckv+CkpCDgpLjgpY3gpLXgpL7gpLjgpY3gpKXgpY3gpK8g4KSy4KWJ4KSV4KSwIiwgInByb29mRGVzYzMiOiAiQUVTLTI1NiDgpK7gpL/gpLLgpL/gpJ/gpY3gpLDgpYAt4KSX4KWN4KSw4KWH4KShIOCkuOCljeCkpeCkvuCkqOClgOCkryDgpI/gpKjgpY3gpJXgpY3gpLDgpL/gpKrgpY3gpLbgpKgg4KSG4KSq4KSV4KWAIOCkl+Cli+CkquCkqOClgOCkr+CkpOCkviDgpKzgpKjgpL7gpI8g4KSw4KSW4KSk4KS+IOCkueCliOClpCIsICJwcm9vZlRpdGxlNCI6ICLgpKTgpYHgpLDgpILgpKQg4KSP4KSG4KSIIOCknOCkvuCkguCkmiIsICJwcm9vZkRlc2M0IjogIuCkrOCkv+CkqOCkviDgpJXgpL/gpLjgpYAg4KSm4KWH4KSw4KWAIOCkleClhyDgpKzgpY3gpLDgpL7gpIngpJzgpLzgpLAg4KSu4KWH4KSCIOCkj+CkhuCkiCDgpLLgpJXgpY3gpLfgpKPgpYvgpIIg4KSV4KS+IOCkpOClgeCksOCkguCkpCDgpLXgpL/gpLbgpY3gpLLgpYfgpLfgpKMg4KSV4KSw4KSk4KS+IOCkueCliOClpCJ9LCAibXIiOiB7InN1YnRpdGxlIjogIuCkhuCkruCljeCkueClgCDgpKTgpYHgpK7gpJrgpY3gpK/gpL4g4KSG4KSw4KWL4KSX4KWN4KSv4KS+4KS44KS+4KSg4KWAIOCkhuCko+CkvyDgpJXgpLLgpY3gpK/gpL7gpKPgpL7gpLjgpL7gpKDgpYAg4KSv4KWH4KSl4KWHIOCkhuCkueCli+CkpC4iLCAib2ZmbGluZU1vZGUiOiAi4KSR4KSr4KSy4KS+4KSI4KSoIOCkruCli+CkoSIsICJvbmxpbmVNb2RlIjogIkFXUyDgpLbgpYAg4KSV4KSo4KWH4KSV4KWN4KSfIOCkleClh+CksuClh+CksuClhyIsICJlbWVyZ2VuY3lIZWxwIjogIuCkpOCkvuCkpOCkoeClgOCkmuClgCDgpK7gpKbgpKQiLCAiZW1lcmdlbmN5RGVzYyI6ICLgpKTgpY3gpLXgpLDgpL/gpKQg4KS14KWI4KSm4KWN4KSv4KSV4KWA4KSvIOCkruCkpuCkpCDgpLngpLXgpYAg4KSG4KS54KWHPyDgpLDgpYHgpJfgpY3gpKPgpLXgpL7gpLngpL/gpJXgpL4g4KSs4KWL4KSy4KS14KS+IOCkleCkv+CkguCkteCkviDgpIbgpLbgpL4g4KSV4KS+4KSw4KWN4KSv4KSV4KSw4KWN4KSk4KWN4KSv4KS+4KSy4KS+IOCkuOClguCkmuCkv+CkpCDgpJXgpLDgpL4uIiwgImNhbGxIZWxwQnRuIjogIuCkhuCkpOCljeCkpOCkvuCkmiDgpK7gpKbgpKTgpYDgpLjgpL7gpKDgpYAg4KSV4KWJ4KSyIOCkleCksOCkviIsICJoZWFsdGhBbGVydCI6ICLgpJfgpL7gpLUg4KSG4KSw4KWL4KSX4KWN4KSvIOCkh+CktuCkvuCksOCkviIsICJuZXdCYWRnZSI6ICLgpKjgpLXgpYDgpKgiLCAiYWxlcnREZXNjIjogIuCkpOClgeCkruCkmuCljeCkr+CkviDgpK3gpL7gpJfgpL7gpKQg4KSk4KS+4KSq4KS+4KSa4KWHIOCksOClgeCkl+CljeCkoyDgpLXgpL7gpKLgpKQg4KSG4KS54KWH4KSkLiDgpLjgpY3gpLXgpJrgpY3gpJsg4KSq4KS+4KSj4KWAIOCkquCljeCkr+CkviDgpIbgpKPgpL8g4KS44KWB4KSw4KSV4KWN4KS34KS/4KSkIOCksOCkvuCkueCkvi4iLCAidmlld0RldGFpbHMiOiAi4KSk4KSq4KS24KWA4KSyIOCkquCkueCkviIsICJhbGVydE1vZGFsVGl0bGUiOiAi4KSX4KS+4KS1IOCkhuCksOCli+Ckl+CljeCkryDgpIfgpLbgpL7gpLDgpL4g4KSk4KSq4KS24KWA4KSyIiwgImFsZXJ0TG9jYXRpb24iOiAi4KS44KWN4KSl4KS+4KSoOiDgpLXgpL7gpLDgpKPgpLjgpYAg4KSc4KS/4KSy4KWN4KS54KS+ICjgpKTgpYHgpK7gpJrgpYcg4KSX4KS+4KS1KSIsICJhbGVydFN0YXR1cyI6ICLgpLjgpY3gpKXgpL/gpKTgpYA6IOCkuOCkleCljeCksOCkv+CkryDgpIbgpLDgpYvgpJfgpY3gpK8g4KS44KSy4KWN4KSy4KS+IiwgImFsZXJ0UHJlY2F1dGlvbjEiOiAi4KSq4KS/4KSj4KWN4KSv4KS+4KSa4KWHIOCkquCkvuCko+ClgCDgpIngpJXgpLPgpLXgpL46IOCknOCksuCknOCkqOCljeCkryDgpLjgpILgpLjgpLDgpY3gpJcg4KSw4KWL4KSW4KSj4KWN4KSv4KS+4KS44KS+4KSg4KWAIOCkuOCksOCljeCktSDgpKrgpL7gpKPgpYAg4KSX4KS+4KSz4KWC4KSoIOCkhuCko+CkvyDgpIngpJXgpLPgpLXgpYLgpKgg4KSq4KWN4KSv4KS+LiIsICJhbGVydFByZWNhdXRpb24yIjogIuCkruCkmuCljeCkm+CksOCkpuCkvuCko+ClgCDgpLXgpL7gpKrgpLDgpL46IOCkleClgOCkn+CkleCknOCkqOCljeCkryDgpIbgpJzgpL7gpLDgpL7gpILgpKrgpL7gpLjgpYLgpKgg4KSs4KSa4KS+4KS14KS+4KS44KS+4KSg4KWAIOCkruCkmuCljeCkm+CksOCkpuCkvuCko+ClgOCkpCDgpJ3gpYvgpKrgpL4uIiwgImFsZXJ0UHJlY2F1dGlvbjMiOiAi4KSG4KS24KS+IOCkleCkvuCksOCljeCkr+CkleCksOCljeCkpOCljeCkr+CkvuCktuClgCDgpLjgpILgpKrgpLDgpY3gpJU6IOCkpOCljeCkteCksOCkv+CkpCDgpIngpKrgpJrgpL7gpLDgpL7gpLjgpL7gpKDgpYAg4KSk4KS+4KSq4KS+4KSa4KWAIOCkruCkvuCkueCkv+CkpOClgCDgpIbgpLbgpL4g4KSV4KS+4KSw4KWN4KSv4KSV4KSw4KWN4KSk4KWN4KSv4KS+4KSy4KS+IOCkpuCljeCkr+Ckvi4iLCAiY2FsbEFzaGEiOiAi4KSG4KSk4KWN4KSk4KS+4KSaIOCkhuCktuCkviDgpJXgpL7gpLDgpY3gpK/gpJXgpLDgpY3gpKTgpY3gpK/gpL7gpLLgpL4g4KSV4KWJ4KSyIOCkleCksOCkviIsICJjbG9zZUJ0biI6ICLgpKzgpILgpKYg4KSV4KSw4KS+IiwgIm15SGVhbHRoU2VydmljZXMiOiAi4KSu4KS+4KSd4KWN4KSv4KS+IOCkhuCksOCli+Ckl+CljeCkryDgpLjgpYfgpLXgpL4iLCAiY2hlY2tTeW1wdG9tcyI6ICLgpLLgpJXgpY3gpLfgpKPgpYcg4KSk4KSq4KS+4KS44KS+IiwgImNoZWNrU3ltcHRvbXNEZXNjIjogIuCkpOClgeCkruCkmuClgCDgpLLgpJXgpY3gpLfgpKPgpYcg4KSk4KSq4KS+4KS44KS+IOCkhuCko+CkvyDgpLjgpLLgpY3gpLLgpL4g4KSu4KS/4KSz4KS14KS+LiIsICJteVJlY29yZHMiOiAi4KSu4KS+4KSd4KWHIOCkhuCksOCli+Ckl+CljeCkryDgpLDgpYfgpJXgpYngpLDgpY3gpKEiLCAibXlSZWNvcmRzRGVzYyI6ICLgpKTgpYHgpK7gpJrgpYcg4KSG4KSw4KWL4KSX4KWN4KSvIOCksOClh+CkleClieCksOCljeCkoSDgpIbgpKPgpL8g4KSu4KS+4KSX4KWA4KSyIOCkpOCkquCkvuCkuOCko+CljeCkr+CkviDgpKrgpLngpL4uIiwgIndvbWVuUHJlZ25hbmN5IjogIuCkruCkueCkv+CksuCkviDgpIbgpKPgpL8g4KSX4KSw4KWN4KSt4KSn4KS+4KSw4KSj4KS+IiwgIndvbWVuUHJlZ25hbmN5RGVzYyI6ICLgpJfgpLDgpY3gpK3gpKfgpL7gpLDgpKPgpL4g4KSV4KS+4KSz4KSc4KWALCDgpK7gpL7gpJfgpYvgpLXgpL4g4KSG4KSj4KS/IOCkuOCkruCksOCljeCkpeCkqC4iLCAiZ292U2NoZW1lcyI6ICLgpLjgpLDgpJXgpL7gpLDgpYAg4KSv4KWL4KSc4KSo4KS+IiwgImdvdlNjaGVtZXNEZXNjIjogIuCkpOClgeCkruCljeCkueClgCDgpKrgpL7gpKTgpY3gpLAg4KSF4KS44KSy4KWH4KSy4KWN4KSv4KS+IOCkr+Cli+CknOCkqOCkviDgpIbgpKPgpL8g4KSr4KS+4KSv4KSm4KWHIOCkpOCkquCkvuCkuOCkvi4iLCAiaGVhbHRoU25hcHNob3QiOiAi4KSk4KWB4KSu4KSa4KS+IOCkhuCksOCli+Ckl+CljeCkryDgpLjgpL7gpLDgpL7gpILgpLYiLCAiaGVhbHRoU2NvcmUiOiAi4KSG4KSw4KWL4KSX4KWN4KSvIOCkp+CkvuCkteCkuOCkguCkluCljeCkr+CkviIsICJoZWFsdGhTY29yZVN0YXR1cyI6ICLgpJrgpL7gpILgpJfgpLLgpYciLCAiY2hlY2t1cHNEb25lIjogIuCkleClh+CksuClh+CksuCljeCkr+CkviDgpKTgpKrgpL7gpLjgpKPgpY3gpK/gpL4iLCAiY2hlY2t1cHNEb25lU3ViIjogIuCkr+CkviDgpLXgpLDgpY3gpLfgpYAiLCAiYWN0aXZlQWxlcnRzIjogIuCkuOCkleCljeCksOCkv+CkryDgpIfgpLbgpL7gpLDgpYciLCAiYWN0aXZlQWxlcnRzU3ViIjogIuCkleClg+CkpOClgCDgpIbgpLXgpLbgpY3gpK/gpJUiLCAibGFzdENoZWNrdXAiOiAi4KS24KWH4KS14KSf4KSa4KWAIOCkpOCkquCkvuCkuOCko+ClgCIsICJkYXlzQWdvIjogIuClp+ClqyDgpKbgpL/gpLXgpLjgpL7gpILgpKrgpYLgpLDgpY3gpLXgpYAiLCAibGFzdENoZWNrdXBEYXRlIjogIuClp+ClqiDgpK7gpYcg4KWo4KWm4KWo4KWrIiwgInByb29mVGl0bGUxIjogIuCkreCkvuCkt+Clh+CkmuClgCDgpJXgpYvgpKPgpKTgpYDgpLngpYAg4KSF4KSfIOCkqOCkvuCkueClgCIsICJwcm9vZkRlc2MxIjogIuCkpOClgeCkruCkmuCljeCkr+CkviDgpK3gpL7gpLfgpYfgpKQgKOCkruCksOCkvuCkoOClgCwg4KS54KS/4KSC4KSm4KWALCDgpKTgpK7gpL/gpLMsIOCkpOClh+CksuClgeCkl+Clgiwg4KSs4KSC4KSX4KS+4KSy4KWAKSDgpKzgpYvgpLLgpL4g4KSV4KS/4KSC4KS14KS+IOCksuCkv+CkueCkvi4iLCAicHJvb2ZUaXRsZTIiOiAi4KSH4KSC4KSf4KSw4KSo4KWH4KSf4KSa4KWAIOCkl+CksOCknCDgpKjgpL7gpLngpYAiLCAicHJvb2ZEZXNjMiI6ICLgpKbgpYHgpLDgpY3gpJfgpK4g4KS24KWH4KSk4KS+4KSk4KS54KWAIOCkhuCksOCli+Ckl+CljeCkryDgpKTgpKrgpL7gpLjgpKPgpYAg4KSV4KSw4KS+OyDgpKjgpYfgpJ/gpLXgpLDgpY3gpJUg4KSG4KSy4KWN4KSv4KS+4KS14KSwIOCkhuCkquCli+CkhuCkqiDgpLjgpL/gpILgpJUg4KS54KWL4KSI4KSyLiIsICJwcm9vZlRpdGxlMyI6ICLgpLjgpYHgpLDgpJXgpY3gpLfgpL/gpKQg4KSG4KSw4KWL4KSX4KWN4KSvIOCksuClieCkleCksCIsICJwcm9vZkRlc2MzIjogIkFFUy0yNTYg4KSu4KS/4KSy4KS/4KSf4KSw4KWALeCkl+CljeCksOClh+CkoSDgpLjgpY3gpKXgpL7gpKjgpL/gpJUg4KSP4KSo4KWN4KSV4KWN4KSw4KS/4KSq4KWN4KS24KSoIOCkpOClgeCkruCkmuClgCDgpJfgpYvgpKrgpKjgpYDgpK/gpKTgpL4g4KS44KWB4KSw4KSV4KWN4KS34KS/4KSkIOCkoOClh+CkteCkpOClhy4iLCAicHJvb2ZUaXRsZTQiOiAi4KSk4KWN4KS14KSw4KS/4KSkIOCkj+CkhuCkryDgpKTgpKrgpL7gpLjgpKPgpYAiLCAicHJvb2ZEZXNjNCI6ICLgpKzgpY3gpLDgpL7gpIngpJ3gpLDgpK7gpKfgpY3gpK/gpYfgpJog4KSP4KSG4KSvIOCkleCli+Cko+CkpOCljeCkr+CkvuCkueClgCDgpLXgpL/gpLLgpILgpKzgpL7gpLbgpL/gpLXgpL7gpK8g4KSy4KSV4KWN4KS34KSj4KS+4KSC4KSa4KWHIOCkpOCljeCkteCksOCkv+CkpCDgpLXgpL/gpLbgpY3gpLLgpYfgpLfgpKMg4KSV4KSw4KSk4KWHLiJ9LCAidGEiOiB7InN1YnRpdGxlIjogIuCuieCumeCvjeCuleCus+CvjSDgrobgrrDgr4vgrpXgr43grpXgrr/grq/grqTgr43grqTgrr/grrHgr43grpXgr4Hgrq7gr40g4K6o4K6y4K+N4K614K6+4K604K+N4K614K6/4K6x4K+N4K6V4K+B4K6u4K+NIOCuieCupOCutSDgrqjgrr7grpngr43grpXgrrPgr40g4K6H4K6w4K+B4K6V4K+N4K6V4K6/4K6x4K+L4K6u4K+NLiIsICJvZmZsaW5lTW9kZSI6ICLgrobgroPgrqrgr43grrLgr4jgrqngr40g4K6q4K6v4K6p4K+N4K6u4K+B4K6x4K+IIiwgIm9ubGluZU1vZGUiOiAiQVdTIOCuieCun+CuqeCvjSDgrofgrqPgr4jgrpXgr43grpXgrqrgr43grqrgrp/gr43grp/gr4HgrrPgr43grrPgrqTgr4EiLCAiZW1lcmdlbmN5SGVscCI6ICLgroXgrrXgrprgrrAg4K6J4K6k4K614K6/IiwgImVtZXJnZW5jeURlc2MiOiAi4K6J4K6f4K6p4K6f4K6/IOCuruCusOCvgeCupOCvjeCupOCvgeCutSDgrongrqTgrrXgrr8g4K6k4K+H4K614K+I4K6v4K6+PyDgrobgrq7gr43grqrgr4HgrrLgrqngr43grrjgr4gg4K6F4K604K+I4K6V4K+N4K6V4K614K+B4K6u4K+NIOCuheCusuCvjeCusuCupOCvgSDgrobgrrfgrr4g4K6q4K6j4K6/4K6v4K6+4K6z4K6w4K+B4K6V4K+N4K6V4K+BIOCupOCvhuCusOCuv+CuteCuv+CuleCvjeCuleCuteCvgeCuruCvjS4iLCAiY2FsbEhlbHBCdG4iOiAi4K6J4K6f4K6p4K6f4K6/4K6v4K6+4K6VIOCuieCupOCuteCuv+CuleCvjeCuleCvgSDgroXgrrTgr4jgrpXgr43grpXgrrXgr4Hgrq7gr40iLCAiaGVhbHRoQWxlcnQiOiAi4K6V4K6/4K6w4K6+4K6uIOCumuCvgeCuleCuvuCupOCuvuCusCDgro7grprgr43grprgrrDgrr/grpXgr43grpXgr4giLCAibmV3QmFkZ2UiOiAi4K6q4K+B4K6k4K6/4K6v4K6k4K+BIiwgImFsZXJ0RGVzYyI6ICLgrongrpngr43grpXgrrPgr40g4K6q4K6V4K+B4K6k4K6/4K6v4K6/4K6y4K+NIOCuleCuvuCur+CvjeCumuCvjeCumuCusuCvjSDgrqrgrr7grqTgrr/grqrgr43grqrgr4HgrpXgrrPgr40g4K6F4K6k4K6/4K6V4K6w4K6/4K6k4K+N4K6k4K+BIOCuteCusOCvgeCuleCuv+CuqeCvjeCuseCuqS4g4K6a4K+B4K6k4K+N4K6k4K6u4K6+4K6pIOCupOCuo+CvjeCuo+CvgOCusOCvjSDgrpXgr4Hgrp/grr/grqTgr43grqTgr4Eg4K6q4K6+4K6k4K+B4K6V4K6+4K6q4K+N4K6q4K6+4K6VIOCuh+CusOCvgeCuleCvjeCuleCuteCvgeCuruCvjS4iLCAidmlld0RldGFpbHMiOiAi4K614K6/4K614K6w4K6Z4K+N4K6V4K6z4K+I4K6V4K+NIOCuleCuvuCuo+CvjeCulSIsICJhbGVydE1vZGFsVGl0bGUiOiAi4K6V4K6/4K6w4K6+4K6uIOCumuCvgeCuleCuvuCupOCuvuCusCDgro7grprgr43grprgrrDgrr/grpXgr43grpXgr4gg4K614K6/4K614K6w4K6Z4K+N4K6V4K6z4K+NIiwgImFsZXJ0TG9jYXRpb24iOiAi4K6H4K6f4K6u4K+NOiDgrrXgrr7grrDgrqPgrr7grprgrr8g4K6u4K6+4K614K6f4K+N4K6f4K6u4K+NICjgrongrpngr43grpXgrrPgr40g4K6V4K6/4K6w4K6+4K6u4K6u4K+NKSIsICJhbGVydFN0YXR1cyI6ICLgrqjgrr/grrLgr4g6IOCumuCvhuCur+CusuCuv+CusuCvjSDgrongrrPgr43grrMg4K6G4K6y4K+L4K6a4K6p4K+IIiwgImFsZXJ0UHJlY2F1dGlvbjEiOiAi4K6V4K+B4K6f4K6/4K6o4K+A4K6w4K+I4K6V4K+NIOCuleCuvuCur+CvjeCumuCvjeCumuCuteCvgeCuruCvjTog4K6o4K+A4K6w4K+NIOCuruCvguCusuCuruCvjSDgrqrgrrDgrrXgr4Hgrq7gr40g4K6k4K+K4K6x4K+N4K6x4K+B4K6V4K6z4K+I4K6k4K+NIOCupOCun+CvgeCuleCvjeCulSDgrqTgrqPgr43grqPgr4DgrrDgr4gg4K614K6f4K6/4K6V4K6f4K+N4K6f4K6/IOCuleCuvuCur+CvjeCumuCvjeCumuCuv+CuleCvjSDgrpXgr4Hgrp/grr/grpXgr43grpXgrrXgr4Hgrq7gr40uIiwgImFsZXJ0UHJlY2F1dGlvbjIiOiAi4K6V4K+K4K6a4K+B4K614K6y4K+I4K6V4K6z4K+I4K6q4K+NIOCuquCur+CuqeCvjeCuquCun+CvgeCupOCvjeCupOCuteCvgeCuruCvjTog4K6V4K+K4K6a4K+B4K6V4K+N4K6V4K6z4K6+4K6y4K+NIOCuquCusOCuteCvgeCuruCvjSDgrqjgr4vgrq/gr43grpXgrrPgr4jgrqTgr40g4K6k4K6f4K+B4K6V4K+N4K6VIOCuleCviuCumuCvgeCuteCusuCviOCuleCvjeCuleCvgeCus+CvjSDgrqTgr4Lgrpngr43grpXgrrXgr4Hgrq7gr40uIiwgImFsZXJ0UHJlY2F1dGlvbjMiOiAi4K6G4K634K6+4K614K+I4K6k4K+NIOCupOCviuCun+CusOCvjeCuquCvgSDgrpXgr4rgrrPgr43grrPgrrXgr4Hgrq7gr406IOCuleCuvuCur+CvjeCumuCvjeCumuCusuCvjSDgroXgrrHgrr/grpXgr4HgrrHgrr/grpXgrrPgr40g4K6H4K6w4K+B4K6o4K+N4K6k4K6+4K6y4K+NIOCuieCun+CuqeCun+Cuv+Cur+CuvuCulSDgrobgrrfgrr4g4K6q4K6j4K6/4K6v4K6+4K6z4K6w4K6/4K6f4K6u4K+NIOCupOCvhuCusOCuv+CuteCuv+CuleCvjeCuleCuteCvgeCuruCvjS4iLCAiY2FsbEFzaGEiOiAi4K6G4K634K6+IOCuquCuo+Cuv+Cur+CuvuCus+CusOCviCDgroXgrrTgr4jgrpXgr43grpXgrrXgr4Hgrq7gr40iLCAiY2xvc2VCdG4iOiAi4K6u4K+C4K6f4K+B4K6VIiwgIm15SGVhbHRoU2VydmljZXMiOiAi4K6O4K6p4K6k4K+BIOCumuCvgeCuleCuvuCupOCuvuCusCDgrprgr4fgrrXgr4jgrpXgrrPgr40iLCAiY2hlY2tTeW1wdG9tcyI6ICLgroXgrrHgrr/grpXgr4HgrrHgrr/grpXgrrPgr4jgrprgr40g4K6a4K6w4K6/4K6q4K6+4K6w4K+N4K6V4K+N4K6V4K614K+B4K6u4K+NIiwgImNoZWNrU3ltcHRvbXNEZXNjIjogIuCuieCumeCvjeCuleCus+CvjSDgroXgrrHgrr/grpXgr4HgrrHgrr/grpXgrrPgr4jgrprgr40g4K6a4K6w4K6/4K6q4K6+4K6w4K+N4K6k4K+N4K6k4K+BIOCuhuCusuCvi+CumuCuqeCviOCuleCus+CviOCuquCvjSDgrqrgr4bgrrHgrrXgr4Hgrq7gr40uIiwgIm15UmVjb3JkcyI6ICLgro7grqngrqTgr4Eg4K6a4K+B4K6V4K6+4K6k4K6+4K6w4K6q4K+NIOCuquCupOCuv+CuteCvgeCuleCus+CvjSIsICJteVJlY29yZHNEZXNjIjogIuCuieCumeCvjeCuleCus+CvjSDgrprgr4HgrpXgrr7grqTgrr7grrDgrqrgr40g4K6q4K6k4K6/4K614K+B4K6V4K6z4K+NIOCuruCuseCvjeCuseCvgeCuruCvjSDgrq7gr4Hgrqjgr43grqTgr4jgrq8g4K6q4K6w4K6/4K6a4K+L4K6k4K6p4K+I4K6V4K6z4K+I4K6V4K+NIOCuleCuvuCuo+CvjeCulS4iLCAid29tZW5QcmVnbmFuY3kiOiAi4K6q4K+G4K6j4K+N4K6V4K6z4K+NICYg4K6V4K6w4K+N4K6q4K+N4K6q4K6u4K+NIiwgIndvbWVuUHJlZ25hbmN5RGVzYyI6ICLgrpXgrrDgr43grqrgr43grqrgrpXgrr7grrIg4K6q4K6w4K6+4K6u4K6w4K6/4K6q4K+N4K6q4K+BLCDgrpXgrqPgr43grpXgrr7grqPgrr/grqrgr43grqrgr4Eg4K6u4K6x4K+N4K6x4K+B4K6u4K+NIOCuhuCupOCusOCuteCvgS4iLCAiZ292U2NoZW1lcyI6ICLgroXgrrDgrprgr4Eg4K6k4K6/4K6f4K+N4K6f4K6Z4K+N4K6V4K6z4K+NIiwgImdvdlNjaGVtZXNEZXNjIjogIuCuqOCvgOCumeCvjeCuleCus+CvjSDgrqTgrpXgr4HgrqTgrr/grq/gr4Hgrp/gr4jgrq8g4K6F4K6w4K6a4K+BIOCupOCuv+Cun+CvjeCun+CumeCvjeCuleCus+CviOCumuCvjSDgrprgrrDgrr/grqrgrr7grrDgr43grpXgr43grpXgrrXgr4Hgrq7gr40uIiwgImhlYWx0aFNuYXBzaG90IjogIuCuieCumeCvjeCuleCus+CvjSDgrprgr4HgrpXgrr7grqTgrr7grrDgrprgr40g4K6a4K+B4K6w4K+B4K6V4K+N4K6V4K6u4K+NIiwgImhlYWx0aFNjb3JlIjogIuCumuCvgeCuleCuvuCupOCuvuCusCDgrq7grqTgrr/grqrgr43grqrgr4bgrqPgr40iLCAiaGVhbHRoU2NvcmVTdGF0dXMiOiAi4K6o4K6p4K+N4K6x4K+BIiwgImNoZWNrdXBzRG9uZSI6ICLgrq7gr4Hgrp/grr/grqjgr43grqQg4K6q4K6w4K6/4K6a4K+L4K6k4K6p4K+I4K6V4K6z4K+NIiwgImNoZWNrdXBzRG9uZVN1YiI6ICLgrofgrqjgr43grqQg4K6G4K6j4K+N4K6f4K+BIiwgImFjdGl2ZUFsZXJ0cyI6ICLgrprgr4bgrq/grrLgrr/grrLgr40g4K6J4K6z4K+N4K6zIOCujuCumuCvjeCumuCusOCuv+CuleCvjeCuleCviOCuleCus+CvjSIsICJhY3RpdmVBbGVydHNTdWIiOiAi4K6J4K6f4K6p4K6f4K6/IOCuqOCun+CuteCun+Cuv+CuleCvjeCuleCviCIsICJsYXN0Q2hlY2t1cCI6ICLgrpXgrp/gr4jgrprgrr8g4K6q4K6w4K6/4K6a4K+L4K6k4K6p4K+IIiwgImRheXNBZ28iOiAiMTUg4K6o4K6+4K6f4K+N4K6V4K6z4K+B4K6V4K+N4K6V4K+BIOCuruCvgeCuqeCvjSIsICJsYXN0Q2hlY2t1cERhdGUiOiAiMTQg4K6u4K+HIDIwMjUiLCAicHJvb2ZUaXRsZTEiOiAi4K6u4K+K4K604K6/4K6k4K+NIOCupOCun+CviCDgrofgrrLgr43grrLgr4giLCAicHJvb2ZEZXNjMSI6ICLgrongrpngr43grpXgrrPgr40g4K6k4K6+4K6v4K+N4K6u4K+K4K604K6/4K6v4K6/4K6y4K+NICjgrqTgrq7grr/grrTgr40sIOCuh+CuqOCvjeCupOCuvywg4K6k4K+G4K6y4K+B4K6Z4K+N4K6V4K+BLCDgrq7grrDgrr7grqTgr43grqTgrr8sIOCuquCvhuCumeCvjeCuleCuvuCusuCuvykg4K6q4K+H4K6a4K6y4K6+4K6u4K+NIOCuheCusuCvjeCusuCupOCvgSDgro7grrTgr4HgrqTgrrLgrr7grq7gr40uIiwgInByb29mVGl0bGUyIjogIuCuh+Cuo+CviOCur+CuruCvjSDgrqTgr4fgrrXgr4jgrq/grr/grrLgr43grrLgr4giLCAicHJvb2ZEZXNjMiI6ICLgrqTgr4rgrrLgr4jgrqTgr4LgrrAg4K614K6v4K6y4K+N4K614K+G4K6z4K6/4K6V4K6z4K6/4K6y4K+B4K6u4K+NIOCuteCvh+CusuCviCDgrprgr4bgrq/gr43grq/gr4Hgrq7gr407IOCuh+Cuo+CviOCur+CuruCvjSDgrpXgrr/grp/gr4jgrqTgr43grqTgrqTgr4Hgrq7gr40g4K6k4K6+4K6p4K6+4K6VIOCukuCupOCvjeCupOCuv+CumuCviOCur+CvgeCuruCvjS4iLCAicHJvb2ZUaXRsZTMiOiAi4K6q4K6+4K6k4K+B4K6V4K6+4K6q4K+N4K6q4K6+4K6pIOCuueCvhuCusuCvjeCupOCvjSDgrrLgrr7grpXgr43grpXgrrDgr40iLCAicHJvb2ZEZXNjMyI6ICJBRVMtMjU2IOCuh+CusOCuvuCuo+CvgeCuteCupOCvjSDgrqTgrrAg4K6V4K+B4K6x4K6/4K6v4K6+4K6V4K+N4K6V4K6u4K+NIOCuieCumeCvjeCuleCus+CvjSDgrq7grrDgr4HgrqTgr43grqTgr4HgrrUg4K614K6/4K614K6w4K6Z4K+N4K6V4K6z4K+I4K6q4K+NIOCuquCuvuCupOCvgeCuleCuvuCuleCvjeCuleCuv+CuseCupOCvgS4iLCAicHJvb2ZUaXRsZTQiOiAi4K6J4K6f4K6p4K6f4K6/IEFJIOCuquCusOCuv+CumuCvi+CupOCuqeCviCIsICJwcm9vZkRlc2M0IjogIuCuieCusuCuvuCuteCuv+Cur+Cuv+CusuCvh+Cur+CvhyBBSSDgroXgrrHgrr/grpXgr4HgrrHgrr/grpXgrrPgr4gg4K6J4K6f4K6p4K6f4K6/4K6v4K6+4K6VIOCuquCuleCvgeCuquCvjeCuquCuvuCur+CvjeCuteCvgSDgrprgr4bgrq/gr43grpXgrr/grrHgrqTgr4EuIn0sICJ0ZSI6IHsic3VidGl0bGUiOiAi4LCu4LGAIOCwhuCwsOCxi+Cwl+CxjeCwr+CwgiDgsK7gsLDgsL/gsK/gsYEg4LC24LGN4LCw4LGH4LCv4LC44LGN4LC44LGB4LCV4LGBIOCwruCwpuCxjeCwpuCwpOCxgSDgsIfgsLXgsY3gsLXgsKHgsL7gsKjgsL/gsJXgsL8g4LCu4LGH4LCu4LGBIOCwh+CwleCxjeCwleCwoSDgsIngsKjgsY3gsKjgsL7gsK7gsYEuIiwgIm9mZmxpbmVNb2RlIjogIuCwhuCwq+CxjeKAjOCwsuCxiOCwqOCxjSDgsK7gsYvgsKHgsY0iLCAib25saW5lTW9kZSI6ICJBV1Mg4LCk4LGLIOCwheCwqOCxgeCwuOCwguCwp+CwvuCwqOCwv+CwguCwmuCwrOCwoeCwv+CwguCwpuCwvyIsICJlbWVyZ2VuY3lIZWxwIjogIuCwheCwpOCxjeCwr+CwteCwuOCwsCDgsLjgsLngsL7gsK/gsIIiLCAiZW1lcmdlbmN5RGVzYyI6ICLgsKTgsJXgsY3gsLfgsKMg4LC14LGI4LCm4LGN4LCvIOCwuOCwueCwvuCwr+CwgiDgsJXgsL7gsLXgsL7gsLLgsL4/IOCwheCwguCwrOCxgeCwsuCxhuCwqOCxjeCwuOCxjSDgsKrgsL/gsLLgsLXgsILgsKHgsL8g4LCy4LGH4LCm4LC+IOCwhuCwtuCwviDgsJXgsL7gsLDgsY3gsK/gsJXgsLDgsY3gsKTgsKjgsYEg4LC44LCC4LCq4LGN4LCw4LCm4LC/4LCC4LCa4LCC4LCh4LC/LiIsICJjYWxsSGVscEJ0biI6ICLgsLjgsLngsL7gsK/gsIIg4LCV4LGL4LC44LCCIOCwh+CwquCxjeCwquCxgeCwoeCxhyDgsJXgsL7gsLLgsY0g4LCa4LGH4LCv4LCC4LCh4LC/IiwgImhlYWx0aEFsZXJ0IjogIuCwl+CxjeCwsOCwvuCwriDgsIbgsLDgsYvgsJfgsY3gsK8g4LC54LGG4LCa4LGN4LCa4LCw4LC/4LCVIiwgIm5ld0JhZGdlIjogIuCwleCxiuCwpOCxjeCwpOCwpuCwvyIsICJhbGVydERlc2MiOiAi4LCu4LGAIOCwquCxjeCwsOCwvuCwguCwpOCwguCwsuCxiyDgsJzgsY3gsLXgsLDgsIIg4LCV4LGH4LC44LGB4LCy4LGBIOCwquCxhuCwsOCxgeCwl+CxgeCwpOCxgeCwqOCxjeCwqOCwvuCwr+Cwvy4g4LC44LGN4LC14LCa4LGN4LCb4LCu4LGI4LCoIOCwqOCxgOCwsOCxgSDgsKTgsY3gsLDgsL7gsJfgsILgsKHgsL8g4LCu4LCw4LC/4LCv4LGBIOCwuOCxgeCwsOCwleCxjeCwt+Cwv+CwpOCwguCwl+CwviDgsIngsILgsKHgsILgsKHgsL8uIiwgInZpZXdEZXRhaWxzIjogIuCwteCwv+CwteCwsOCwvuCwsuCxgSDgsJrgsYLgsKHgsILgsKHgsL8iLCAiYWxlcnRNb2RhbFRpdGxlIjogIuCwl+CxjeCwsOCwvuCwriDgsIbgsLDgsYvgsJfgsY3gsK8g4LC54LGG4LCa4LGN4LCa4LCw4LC/4LCVIOCwteCwv+CwteCwsOCwvuCwsuCxgSIsICJhbGVydExvY2F0aW9uIjogIuCwquCxjeCwsOCwpuCxh+CwtuCwgjog4LC14LC+4LCw4LCj4LC+4LC44LC/IOCwnOCwv+CwsuCxjeCwsuCwviAo4LCu4LGAIOCwl+CxjeCwsOCwvuCwruCwgikiLCAiYWxlcnRTdGF0dXMiOiAi4LC44LGN4LCl4LC/4LCk4LC/OiDgsJXgsY3gsLDgsL/gsK/gsL7gsLbgsYDgsLIg4LCG4LCw4LGL4LCX4LGN4LCvIOCwuOCwsuCwueCwviIsICJhbGVydFByZWNhdXRpb24xIjogIuCwpOCxjeCwsOCwvuCwl+CxgeCwqOCxgOCwn+Cwv+CwqOCwvyDgsK7gsLDgsL/gsJfgsL/gsILgsJrgsILgsKHgsL86IOCwqOCxgOCwn+CwvyDgsKbgsY3gsLXgsL7gsLDgsL4g4LC14LGN4LCv4LC+4LCq4LC/4LCC4LCa4LGHIOCwh+CwqOCxjeCwq+CxhuCwleCxjeCwt+CwqOCxjeCwsuCwqOCxgSDgsKjgsL/gsLXgsL7gsLDgsL/gsILgsJrgsKHgsL7gsKjgsL/gsJXgsL8g4LCo4LGA4LCf4LC/4LCo4LC/IOCwteCwoeCwquCxi+CwuOCwvyDgsK7gsLDgsL/gsJfgsL/gsILgsJrgsILgsKHgsL8uIiwgImFsZXJ0UHJlY2F1dGlvbjIiOiAi4LCm4LGL4LCu4LCk4LGG4LCw4LCy4LCo4LGBIOCwteCwvuCwoeCwguCwoeCwvzog4LCm4LGL4LCu4LCyIOCwpuCxjeCwteCwvuCwsOCwviDgsLXgsY3gsK/gsL7gsKrgsL/gsILgsJrgsYcg4LC14LGN4LCv4LC+4LCn4LGB4LCy4LCo4LGBIOCwqOCwv+CwteCwvuCwsOCwv+CwguCwmuCwoeCwvuCwqOCwv+CwleCwvyDgsKbgsYvgsK7gsKTgsYbgsLDgsLIg4LCV4LGN4LCw4LC/4LCC4LCmIOCwqOCwv+CwpuCxjeCwsOCwv+CwguCwmuCwguCwoeCwvy4iLCAiYWxlcnRQcmVjYXV0aW9uMyI6ICLgsIbgsLbgsL4g4LC44LCC4LCq4LGN4LCw4LCm4LC/4LCC4LCq4LGB4LCy4LGBOiDgsKTgsJXgsY3gsLfgsKMg4LCa4LC/4LCV4LC/4LCk4LGN4LC4IOCwleCxi+CwuOCwgiDgsJzgsY3gsLXgsLDgsIIg4LCy4LCV4LGN4LC34LCj4LC+4LCy4LCo4LGBIOCwteCxhuCwguCwn+CwqOCxhyDgsIbgsLbgsL4g4LCV4LC+4LCw4LGN4LCv4LCV4LCw4LGN4LCk4LCV4LGBIOCwpOCxhuCwsuCwv+Cwr+CwnOCxh+Cwr+CwguCwoeCwvy4iLCAiY2FsbEFzaGEiOiAi4LCG4LC24LC+IOCwleCwvuCwsOCxjeCwr+CwleCwsOCxjeCwpOCwleCxgSDgsJXgsL7gsLLgsY0g4LCa4LGH4LCv4LCC4LCh4LC/IiwgImNsb3NlQnRuIjogIuCwruCxguCwuOCwv+CwteCxh+Cwr+CwguCwoeCwvyIsICJteUhlYWx0aFNlcnZpY2VzIjogIuCwqOCwviDgsIbgsLDgsYvgsJfgsY3gsK8g4LC44LGH4LC14LCy4LGBIiwgImNoZWNrU3ltcHRvbXMiOiAi4LCy4LCV4LGN4LC34LCj4LC+4LCy4LCo4LGBIOCwpOCwqOCwv+CwluCxgCDgsJrgsYfgsK/gsILgsKHgsL8iLCAiY2hlY2tTeW1wdG9tc0Rlc2MiOiAi4LCu4LGAIOCwsuCwleCxjeCwt+Cwo+CwvuCwsuCwqOCxgSDgsKTgsKjgsL/gsJbgsYAg4LCa4LGH4LCv4LCC4LCh4LC/IOCwruCwsOCwv+Cwr+CxgSDgsLjgsLLgsLngsL7gsLLgsYEg4LCq4LGK4LCC4LCm4LCC4LCh4LC/LiIsICJteVJlY29yZHMiOiAi4LCo4LC+IOCwhuCwsOCxi+Cwl+CxjeCwryDgsLDgsL/gsJXgsL7gsLDgsY3gsKHgsYHgsLLgsYEiLCAibXlSZWNvcmRzRGVzYyI6ICLgsK7gsYAg4LCG4LCw4LGL4LCX4LGN4LCvIOCwsOCwv+CwleCwvuCwsOCxjeCwoeCxgeCwsuCxgSDgsK7gsLDgsL/gsK/gsYEg4LCX4LCkIOCwquCwsOCxgOCwleCxjeCwt+CwsuCwqOCxgSDgsLXgsYDgsJXgsY3gsLfgsL/gsILgsJrgsILgsKHgsL8uIiwgIndvbWVuUHJlZ25hbmN5IjogIuCwruCwueCwv+Cws+CwsuCxgSAmIOCwl+CwsOCxjeCwreCwp+CwvuCwsOCwoyIsICJ3b21lblByZWduYW5jeURlc2MiOiAi4LCX4LCw4LGN4LCt4LCn4LC+4LCw4LCjIOCwuOCwguCwsOCwleCxjeCwt+Cwoywg4LCq4LCw4LGN4LCv4LC14LGH4LCV4LGN4LC34LCjIOCwruCwsOCwv+Cwr+CxgSDgsK7gsKbgsY3gsKbgsKTgsYEuIiwgImdvdlNjaGVtZXMiOiAi4LCq4LGN4LCw4LCt4LGB4LCk4LGN4LC1IOCwquCwpeCwleCwvuCwsuCxgSIsICJnb3ZTY2hlbWVzRGVzYyI6ICLgsK7gsYDgsLDgsYEg4LCF4LCw4LGN4LC54LGB4LCy4LGI4LCoIOCwquCxjeCwsOCwreCxgeCwpOCxjeCwtSDgsKrgsKXgsJXgsL7gsLLgsKjgsYEg4LCk4LCo4LC/4LCW4LGAIOCwmuCxh+Cwr+CwguCwoeCwvy4iLCAiaGVhbHRoU25hcHNob3QiOiAi4LCu4LGAIOCwhuCwsOCxi+Cwl+CxjeCwryDgsLjgsL7gsLDgsL7gsILgsLbgsIIiLCAiaGVhbHRoU2NvcmUiOiAi4LCG4LCw4LGL4LCX4LGN4LCvIOCwuOCxjeCwleCxi+CwsOCxgSIsICJoZWFsdGhTY29yZVN0YXR1cyI6ICLgsKzgsL7gsJfgsYHgsILgsKbgsL8iLCAiY2hlY2t1cHNEb25lIjogIuCwmuCxh+CwuOCwv+CwqCDgsKrgsLDgsYDgsJXgsY3gsLfgsLLgsYEiLCAiY2hlY2t1cHNEb25lU3ViIjogIuCwiCDgsLjgsILgsLXgsKTgsY3gsLjgsLDgsIIiLCAiYWN0aXZlQWxlcnRzIjogIuCwleCxjeCwsOCwv+Cwr+CwvuCwtuCxgOCwsiDgsLngsYbgsJrgsY3gsJrgsLDgsL/gsJXgsLLgsYEiLCAiYWN0aXZlQWxlcnRzU3ViIjogIuCwmuCwsOCxjeCwryDgsIXgsLXgsLjgsLDgsIIiLCAibGFzdENoZWNrdXAiOiAi4LCa4LC/4LC14LCw4LC/IOCwquCwsOCxgOCwleCxjeCwtyIsICJkYXlzQWdvIjogIjE1IOCwsOCxi+CwnOCxgeCwsiDgsJXgsY3gsLDgsL/gsKTgsIIiLCAibGFzdENoZWNrdXBEYXRlIjogIjE0IOCwruCxhyAyMDI1IiwgInByb29mVGl0bGUxIjogIuCwreCwvuCwt+CwviDgsKrgsLDgsK7gsYjgsKgg4LCF4LCh4LGN4LCh4LCC4LCV4LGB4LCy4LGBIOCwsuCxh+CwteCxgSIsICJwcm9vZkRlc2MxIjogIuCwruCxgCDgsLjgsYrgsILgsKQg4LCt4LC+4LC34LCy4LGLICjgsKTgsYbgsLLgsYHgsJfgsYEsIOCwueCwv+CwguCwpuCxgCwg4LCk4LCu4LC/4LCz4LCCLCDgsK7gsLDgsL7gsKDgsYAsIOCwrOCxhuCumeCvjeCuleCwvuCwsuCxgCkg4LCu4LC+4LCf4LGN4LCy4LC+4LCh4LCC4LCh4LC/IOCwsuCxh+CwpuCwviDgsLDgsL7gsK/gsILgsKHgsL8uIiwgInByb29mVGl0bGUyIjogIuCwh+CwguCwn+CwsOCxjeCwqOCxhuCwn+CxjSDgsIXgsLXgsLjgsLDgsIIg4LCy4LGH4LCm4LGBIiwgInByb29mRGVzYzIiOiAi4LCm4LGC4LCw4LCq4LGN4LCw4LC+4LCC4LCkIOCwquCxiuCwsuCwvuCwsuCxjeCwsuCxiyDgsJXgsYLgsKHgsL4g4LCq4LCo4LC/4LCa4LGH4LC44LGN4LCk4LGB4LCC4LCm4LC/OyDgsJXgsKjgsYbgsJXgsY3gsJ/gsL/gsLXgsL/gsJ/gsYAg4LCw4LC+4LCX4LC+4LCo4LGHIOCwhuCwn+Cxi+CwruCxh+Cwn+Cwv+CwleCxjeKAjOCwl+CwviDgsLjgsL/gsILgsJXgsY0g4LCF4LC14LGB4LCk4LGB4LCC4LCm4LC/LiIsICJwcm9vZlRpdGxlMyI6ICLgsLjgsYHgsLDgsJXgsY3gsLfgsL/gsKQg4LC54LGG4LCy4LGN4LCk4LGNIOCwsuCwvuCwleCwsOCxjSIsICJwcm9vZkRlc2MzIjogIkFFUy0yNTYg4LCu4LC/4LCy4LC/4LCf4LCw4LGALeCwl+CxjeCwsOCxh+CwoeCxjSDgsLjgsY3gsKXgsL7gsKjgsL/gsJUg4LCO4LCo4LGN4oCM4LCV4LGN4LCw4LC/4LCq4LGN4LC34LCo4LGNIOCwruCxgCDgsLXgsY3gsK/gsJXgsY3gsKTgsL/gsJfgsKQg4LCX4LGL4LCq4LGN4LCv4LCk4LCo4LGBIOCwleCwvuCwquCwvuCwoeCxgeCwpOCxgeCwguCwpuCwvy4iLCAicHJvb2ZUaXRsZTQiOiAi4LCk4LCV4LGN4LC34LCjIEFJIOCwteCwv+CwtuCxjeCwsuCxh+Cwt+CwoyIsICJwcm9vZkRlc2M0IjogIuCwrOCxjeCwsOCxjOCwnOCwsOCxjeKAjOCwsuCxi+CwqOCxhyBBSSDgsK7gsYAg4LCy4LCV4LGN4LC34LCj4LC+4LCy4LCo4LGBIOCwpOCwleCxjeCwt+Cwo+CwruCxhyDgsLXgsL/gsLbgsY3gsLLgsYfgsLfgsL/gsLjgsY3gsKTgsYHgsILgsKbgsL8uIn0sICJibiI6IHsic3VidGl0bGUiOiAi4KaG4Kau4Kaw4Ka+IOCmhuCmquCmqOCmvuCmsCDgprjgp43gpqzgpr7gprjgp43gpqXgp43gpq8g4KaP4Kas4KaCIOCmleCmsuCnjeCmr+CmvuCmo+Cnh+CmsCDgppzgpqjgp43gpq8g4KaP4KaW4Ka+4Kao4KeHIOCmhuCmm+Cmv+ClpCIsICJvZmZsaW5lTW9kZSI6ICLgpoXgpqvgprLgpr7gpofgpqgg4Kau4KeL4KahIiwgIm9ubGluZU1vZGUiOiAiQVdTIOCmj+CmsCDgprjgpr7gpqXgp4cg4Ka44KaC4Kav4KeB4KaV4KeN4KakIiwgImVtZXJnZW5jeUhlbHAiOiAi4Kac4Kaw4KeB4Kaw4KeAIOCmuOCmvuCmueCmvuCmr+CnjeCmryIsICJlbWVyZ2VuY3lEZXNjIjogIuCmpOCmvuCmpOCnjeCmleCnjeCmt+Cmo+Cmv+CmlSDgpprgpr/gppXgpr/gp47gprjgpr4g4Ka44Ka+4Ka54Ka+4Kav4KeN4KavIOCmquCnjeCmsOCmr+CmvOCni+CmnOCmqD8g4KaF4KeN4Kav4Ka+4Kau4KeN4Kas4KeB4Kay4KeH4Kao4KeN4Ka4IOCmoeCmvuCmleCngeCmqCDgpqzgpr4g4KaG4Ka24Ka+IOCmleCmsOCnjeCmruCngOCmleCnhyDgprjgpqTgprDgp43gppUg4KaV4Kaw4KeB4Kao4KWkIiwgImNhbGxIZWxwQnRuIjogIuCmuOCmvuCmueCmvuCmr+CnjeCmr+Cnh+CmsCDgppzgpqjgp43gpq8g4KaP4KaW4Kao4KaHIOCmleCmsiDgppXgprDgp4HgpqgiLCAiaGVhbHRoQWxlcnQiOiAi4KaX4KeN4Kaw4Ka+4KauIOCmuOCnjeCmrOCmvuCmuOCnjeCmpeCnjeCmryDgprjgpqTgprDgp43gppXgpqTgpr4iLCAibmV3QmFkZ2UiOiAi4Kao4Kak4KeB4KaoIiwgImFsZXJ0RGVzYyI6ICLgpobgpqrgpqjgpr7gprAg4KaP4Kay4Ka+4KaV4Ka+4Kav4Ka8IOCmnOCnjeCmrOCmsOCnh+CmsCDgpqrgp43gprDgppXgp4vgpqog4Kas4Ka+4Kah4Ka84Kab4KeH4KWkIOCmquCmsOCmv+Cmt+CnjeCmleCmvuCmsCDgppzgprIg4Kaq4Ka+4KaoIOCmleCmsOCngeCmqCDgpo/gpqzgpoIg4Kao4Ka/4Kaw4Ka+4Kaq4KamIOCmpeCmvuCmleCngeCmqOClpCIsICJ2aWV3RGV0YWlscyI6ICLgpqzgpr/gprjgp43gpqTgpr7gprDgpr/gpqQg4Kam4KeH4KaW4KeB4KaoIiwgImFsZXJ0TW9kYWxUaXRsZSI6ICLgppfgp43gprDgpr7gpq4g4Ka44KeN4Kas4Ka+4Ka44KeN4Kal4KeN4KavIOCmuOCmpOCmsOCnjeCmleCmpOCmviDgpqzgpr/gpqzgprDgpqMiLCAiYWxlcnRMb2NhdGlvbiI6ICLgprjgp43gpqXgpr7gpqg6IOCmrOCmvuCmsOCmvuCmo+CmuOCngCDgppzgp4fgprLgpr4gKOCmhuCmquCmqOCmvuCmsCDgppfgp43gprDgpr7gpq4pIiwgImFsZXJ0U3RhdHVzIjogIuCmheCmrOCmuOCnjeCmpeCmvjog4Ka44KaV4KeN4Kaw4Ka/4Kav4Ka8IOCmuOCnjeCmrOCmvuCmuOCnjeCmpeCnjeCmryDgpqjgpr/gprDgp43gpqbgp4fgprbgpr/gppXgpr4iLCAiYWxlcnRQcmVjYXV0aW9uMSI6ICLgppzgprIg4Kar4KeB4Kaf4Ka/4Kav4Ka84KeHIOCmquCmvuCmqCDgppXgprDgp4Hgpqg6IOCmquCmvuCmqOCngOCmr+CmvCDgppzgprIg4Kar4Ka/4Kay4KeN4Kaf4Ka+4KawIOCmleCmsOCnhyDgpqvgp4Hgpp/gpr/gpq/gprzgp4cg4Kaq4Ka+4KaoIOCmleCmsOCngeCmqOClpCIsICJhbGVydFByZWNhdXRpb24yIjogIuCmruCmtuCmvuCmsOCngCDgpqzgp43gpq/gpqzgprngpr7gprAg4KaV4Kaw4KeB4KaoOiDgpq7gprbgpr7gpqzgpr7gprngpr/gpqQg4Kaw4KeL4KaXIOCmquCnjeCmsOCmpOCmv+CmsOCni+Cmp+CnhyDgpq7gprbgpr7gprDgp4Ag4KaW4Ka+4Kaf4Ka/4Kav4Ka84KeHIOCmmOCngeCmruCmvuCmqOClpCIsICJhbGVydFByZWNhdXRpb24zIjogIuCmhuCmtuCmviDgppXgprDgp43gpq7gp4Ag4Kav4KeL4KaX4Ka+4Kav4KeL4KaXOiDgpqbgp43gprDgp4HgpqQg4Kaa4Ka/4KaV4Ka/4KeO4Ka44Ka+4KawIOCmnOCmqOCnjeCmryDgppzgp43gpqzgprDgp4fgprAg4Kay4KaV4KeN4Ka34KajIOCmhuCmtuCmviDgppXgprDgp43gpq7gp4DgppXgp4cg4Kac4Ka+4Kao4Ka+4Kao4KWkIiwgImNhbGxBc2hhIjogIuCmhuCmtuCmviDgppXgprDgp43gpq7gp4DgppXgp4cg4KaV4KayIOCmleCmsOCngeCmqCIsICJjbG9zZUJ0biI6ICLgpqzgpqjgp43gpqcg4KaV4Kaw4KeB4KaoIiwgIm15SGVhbHRoU2VydmljZXMiOiAi4KaG4Kau4Ka+4KawIOCmuOCnjeCmrOCmvuCmuOCnjeCmpeCnjeCmryDgpqrgprDgpr/gprfgp4fgpqzgpr4iLCAiY2hlY2tTeW1wdG9tcyI6ICLgpongpqrgprjgprDgp43gppcg4Kaq4Kaw4KeA4KaV4KeN4Ka34Ka+IOCmleCmsOCngeCmqCIsICJjaGVja1N5bXB0b21zRGVzYyI6ICLgpobgpqrgpqjgpr7gprAg4KaJ4Kaq4Ka44Kaw4KeN4KaX4KaX4KeB4Kay4Ka/IOCmquCmsOCngOCmleCnjeCmt+CmviDgppXgprDgp4Hgpqgg4KaP4Kas4KaCIOCmquCmsOCmvuCmruCmsOCnjeCmtiDgpqrgpr7gpqjgpaQiLCAibXlSZWNvcmRzIjogIuCmhuCmruCmvuCmsCDgprjgp43gpqzgpr7gprjgp43gpqXgp43gpq8g4Kaw4KeH4KaV4Kaw4KeN4KahIiwgIm15UmVjb3Jkc0Rlc2MiOiAi4KaG4Kaq4Kao4Ka+4KawIOCmuOCnjeCmrOCmvuCmuOCnjeCmpeCnjeCmryDgprDgp4fgppXgprDgp43gpqEg4KaP4Kas4KaCIOCmhuCml+Cnh+CmsCDgpprgp4fgppXgpobgpqrgppfgp4HgprLgpr8g4Kam4KeH4KaW4KeB4Kao4KWkIiwgIndvbWVuUHJlZ25hbmN5IjogIuCmqOCmvuCmsOCngCDgppMg4KaX4Kaw4KeN4Kat4Ka+4Kas4Ka44KeN4Kal4Ka+IiwgIndvbWVuUHJlZ25hbmN5RGVzYyI6ICLgppfgprDgp43gpq3gpr7gpqzgprjgp43gpqXgpr7gprAg4Kav4Kak4KeN4KaoLCDgpp/gp43gprDgp43gpq/gpr7gppXgpr/gpoIg4KaP4Kas4KaCIOCmuOCmueCmvuCmr+CmvOCmpOCmvuClpCIsICJnb3ZTY2hlbWVzIjogIuCmuOCmsOCmleCmvuCmsOCmvyDgpqrgp43gprDgppXgprLgp43gpqoiLCAiZ292U2NoZW1lc0Rlc2MiOiAi4KaG4Kaq4Kao4Ka+4KawIOCmr+Cni+Cml+CnjeCmryDgprjgprDgppXgpr7gprDgpr8g4Kaq4KeN4Kaw4KaV4Kay4KeN4Kaq4KaX4KeB4Kay4Ka/IOCmquCmsOCngOCmleCnjeCmt+CmviDgppXgprDgp4HgpqjgpaQiLCAiaGVhbHRoU25hcHNob3QiOiAi4KaG4Kaq4Kao4Ka+4KawIOCmuOCnjeCmrOCmvuCmuOCnjeCmpeCnjeCmryDgprjgpr7gprDgpr7gpoLgprYiLCAiaGVhbHRoU2NvcmUiOiAi4Ka44KeN4Kas4Ka+4Ka44KeN4Kal4KeN4KavIOCmuOCnjeCmleCni+CmsCIsICJoZWFsdGhTY29yZVN0YXR1cyI6ICLgpq3gpr7gprLgp4siLCAiY2hlY2t1cHNEb25lIjogIuCmuOCmruCnjeCmquCmqOCnjeCmqCDgpprgp4fgppXgpobgpqoiLCAiY2hlY2t1cHNEb25lU3ViIjogIuCmj+CmhyDgpqzgppvgprAiLCAiYWN0aXZlQWxlcnRzIjogIuCmuOCmleCnjeCmsOCmv+Cmr+CmvCDgprjgpqTgprDgp43gppXgpqTgpr4iLCAiYWN0aXZlQWxlcnRzU3ViIjogIuCmquCmpuCmleCnjeCmt+Cnh+CmqiDgpqrgp43gprDgpq/gprzgp4vgppzgpqgiLCAibGFzdENoZWNrdXAiOiAi4Ka24KeH4Ka3IOCmmuCnh+CmleCmhuCmqiIsICJkYXlzQWdvIjogIuCnp+CnqyDgpqbgpr/gpqgg4KaG4KaX4KeHIiwgImxhc3RDaGVja3VwRGF0ZSI6ICLgp6fgp6og4Kau4KeHIOCnqOCnpuCnqOCnqyIsICJwcm9vZlRpdGxlMSI6ICLgpq3gpr7gprfgpr7gprAg4KaV4KeL4Kao4KeLIOCmrOCmvuCmp+CmviDgpqjgp4fgpociLCAicHJvb2ZEZXNjMSI6ICLgpobgpqrgpqjgpr7gprAg4Kau4Ka+4Kak4KeD4Kat4Ka+4Ka34Ka+4Kav4Ka8ICjgpqzgpr7gpoLgprLgpr4sIOCmueCmv+CmqOCnjeCmpuCmvywg4Kak4Ka+4Kau4Ka/4KayLCDgpqTgp4fgprLgp4Hgppfgp4EsIOCmruCmvuCmsOCmvuCmoOCmvykg4Kas4Kay4KeB4KaoIOCmrOCmviDgprLgpr/gppbgp4HgpqjgpaQiLCAicHJvb2ZUaXRsZTIiOiAi4KaH4Kao4KeN4Kaf4Ka+4Kaw4Kao4KeH4Kaf4KeH4KawIOCmquCnjeCmsOCmr+CmvOCni+CmnOCmqCDgpqjgp4fgpociLCAicHJvb2ZEZXNjMiI6ICLgpqbgp4HgprDgp43gppfgpq4g4Kau4Ka+4Kag4KeH4KawIOCmruCmp+CnjeCmr+Cnh+CmkyDgppXgpr7gppwg4KaV4Kaw4KeHOyDgpqjgp4fgpp/gppPgpq/gprzgpr7gprDgp43gppUg4KaP4Kay4KeHIOCmuOCnjeCmrOCmr+CmvOCmguCmleCnjeCmsOCmv+Cmr+CmvOCmreCmvuCmrOCnhyDgprjgpr/gppngp43gppUg4Ka54Kav4Ka84KWkIiwgInByb29mVGl0bGUzIjogIuCmuOCngeCmsOCmleCnjeCmt+Cmv+CmpCDgprngp4fgprLgpqUg4Kay4KaV4Ka+4KawIiwgInByb29mRGVzYzMiOiAiQUVTLTI1NiDgpq7gpr/gprLgpr/gpp/gpr7gprDgpr8t4KaX4KeN4Kaw4KeH4KahIOCmuOCnjeCmpeCmvuCmqOCngOCmr+CmvCDgpo/gpqjgppXgp43gprDgpr/gpqrgprbgpqgg4KaG4Kaq4Kao4Ka+4KawIOCml+Cni+CmquCmqOCngOCmr+CmvOCmpOCmviDgprDgppXgp43gprfgpr4g4KaV4Kaw4KeH4KWkIiwgInByb29mVGl0bGU0IjogIuCmpOCmvuCmpOCnjeCmleCnjeCmt+Cmo+Cmv+CmlSDgpo/gpobgpocg4Kaq4Kaw4KeA4KaV4KeN4Ka34Ka+IiwgInByb29mRGVzYzQiOiAi4Kas4KeN4Kaw4Ka+4KaJ4Kac4Ka+4Kaw4KeH4KawIOCmruCmp+CnjeCmr+Cnh+CmhyDgpo/gpobgpocg4KaF4Kas4Ka/4Kay4Kau4KeN4Kas4KeHIOCmieCmquCmuOCmsOCnjeCml+Cnh+CmsCDgpqTgpr7gpqTgp43gppXgp43gprfgpqPgpr/gppUg4Kas4Ka/4Ka24KeN4Kay4KeH4Ka34KajIOCmleCmsOCnh+ClpCJ9fQ==";

const decodeBase64Utf8 = (base64Str) => {
  const binaryString = atob(base64Str);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  const decoder = new TextDecoder('utf-8');
  return JSON.parse(decoder.decode(bytes));
};

const localTranslations = decodeBase64Utf8(base64Translations);

export default function VillagerDashboard() {
  const { lang } = useLanguage();
  const { user } = useAuth();
  const navigate = useNavigate();
  
  const [isOffline, setIsOffline] = useState(
    localStorage.getItem('simulated_network_state') === 'offline'
  );
  const [alertModalOpen, setAlertModalOpen] = useState(false);

  // Sync simulated network status
  const toggleDashboardOffline = () => {
    const nextState = !isOffline;
    setIsOffline(nextState);
    const simState = nextState ? 'offline' : 'online';
    localStorage.setItem('simulated_network_state', simState);
    window.dispatchEvent(new Event(simState));
  };

  useEffect(() => {
    const handleOnline = () => setIsOffline(false);
    const handleOffline = () => setIsOffline(true);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  const userName = user?.name || 'Ramesh';
  const translations = localTranslations[lang] || localTranslations.en;

  // Stagger animation container
  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.08 }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    show: { y: 0, opacity: 1, transition: { type: 'spring', stiffness: 120, damping: 18 } }
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] font-sans antialiased text-[#1E293B] flex flex-col justify-between">
      
      {/* Container wrapper for Navbar and Main content */}
      <div className="w-full">
        {/* Standard Navbar (Restores bottom mobile bar, hamburger menu, routing, and PWA prompts) */}
        <Navbar />

        {/* â”€â”€ MAIN DASHBOARD VIEWPORT â”€â”€ */}
        <main className="max-w-[85rem] mx-auto px-6 py-8 md:px-12 space-y-10 pb-20">
          
          {/* Welcome Heading (Placed cleanly at the top of the dashboard content) */}
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 pb-6 border-b border-slate-200/60">
            <div>
              <h1 className="text-3xl font-black text-slate-900 leading-tight">
                {lang === 'hi' ? `नमस्ते, ${userName} 🙏` : lang === 'mr' ? `नमस्ते, ${userName} 🙏` : lang === 'ta' ? `வணக்கம், ${userName} 🙏` : lang === 'te' ? `నమస్తే, ${userName} 🙏` : lang === 'bn' ? `নমস্কার, ${userName} 🙏` : `Namaste, ${userName} 🙏`}
              </h1>
              <p className="text-sm text-slate-500 font-bold mt-1">
                {translations.subtitle}
              </p>
            </div>
            
            {/* Dynamic Network / Connection Status Indicator */}
            <div className="flex items-center gap-3">
              <button
                onClick={toggleDashboardOffline}
                className={`flex items-center gap-2 px-4 py-2 rounded-full border text-xs font-bold transition-all shadow-sm active:scale-95 ${
                  isOffline
                    ? 'bg-rose-50 border-rose-200 text-rose-600 hover:bg-rose-100'
                    : 'bg-emerald-50 border-emerald-100 text-emerald-700 hover:bg-emerald-100'
                }`}
              >
                {isOffline ? (
                  <>
                    <WifiOff className="w-4 h-4 text-rose-500 animate-pulse" />
                    <span>{translations.offlineMode}</span>
                  </>
                ) : (
                  <>
                    <Wifi className="w-4 h-4 text-emerald-600" />
                    <span>{translations.onlineMode}</span>
                  </>
                )}
              </button>
            </div>
          </div>
          
          {/* Row 1: Side-by-Side Priority Cards */}
          <section className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            
            {/* Card 1: Emergency Help Card */}
            <motion.div
              initial={{ opacity: 0, x: -15 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              className="bg-[#FEF2F2] border border-[#FEE2E2] rounded-3xl p-6 md:p-8 flex flex-col justify-between shadow-sm relative overflow-hidden group hover:shadow-md transition-shadow"
            >
              <div className="absolute top-[-30%] right-[-10%] w-48 h-48 bg-rose-200/20 rounded-full blur-3xl pointer-events-none" />
              
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="w-14 h-14 bg-white border border-rose-200 rounded-full flex items-center justify-center shadow-inner text-rose-600">
                      <Truck className="w-7 h-7" />
                    </div>
                    <h3 className="text-xl font-extrabold text-[#991B1B]">{translations.emergencyHelp}</h3>
                  </div>
                  <span className="px-3 py-1 bg-white border border-rose-200 text-rose-600 text-xs font-bold rounded-full shadow-sm">
                    SOS
                  </span>
                </div>
                
                <p className="text-sm md:text-base text-rose-800 font-semibold leading-relaxed">
                  {translations.emergencyDesc}
                </p>
              </div>

              <Link
                to="/ambulance"
                className="mt-6 w-full py-3.5 bg-[#DC2626] hover:bg-[#B91C1C] text-white rounded-2xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 shadow-[0_4px_12px_rgba(220,38,38,0.25)] transition-all transform active:scale-98"
              >
                <Phone className="w-4 h-4 fill-white" />
                <span>{translations.callHelpBtn}</span>
              </Link>
            </motion.div>

            {/* Card 2: Village Health Alert Card */}
            <motion.div
              initial={{ opacity: 0, x: 15 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              className="bg-[#FFFBEB] border border-[#FEF3C7] rounded-3xl p-6 md:p-8 flex flex-col justify-between shadow-sm relative overflow-hidden group hover:shadow-md transition-shadow"
            >
              <div className="absolute top-[-30%] right-[-10%] w-48 h-48 bg-amber-200/20 rounded-full blur-3xl pointer-events-none" />
              
              <div className="space-y-4">
                <div className="flex items-start gap-4">
                  <div className="w-14 h-14 bg-white border border-amber-200 rounded-2xl flex items-center justify-center shadow-inner text-[#D97706] shrink-0">
                    <AlertTriangle className="w-8 h-8" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="text-xl font-extrabold text-[#92400E]">{translations.healthAlert}</h3>
                      <span className="px-2 py-0.5 bg-[#FEF2F2] border border-[#FEE2E2] text-rose-600 text-[10px] font-black rounded-full uppercase tracking-wider shadow-sm">
                        {translations.newBadge}
                      </span>
                    </div>
                    <p className="text-sm md:text-base text-amber-800 font-semibold leading-relaxed mt-2">
                      {translations.alertDesc}
                    </p>
                  </div>
                </div>
              </div>

              <button
                onClick={() => setAlertModalOpen(true)}
                className="mt-6 self-end flex items-center gap-1.5 text-sm font-black text-[#B45309] hover:text-[#92400E] transition-colors"
              >
                <span>{translations.viewDetails}</span>
                <ChevronRight className="w-4 h-4" />
              </button>
            </motion.div>

          </section>

          {/* Row 2: My Health Services Grid */}
          <section className="space-y-5">
            <h3 className="text-lg font-black text-slate-800 tracking-tight">
              {translations.myHealthServices}
            </h3>
            
            <motion.div
              variants={containerVariants}
              initial="hidden"
              animate="show"
              className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
            >
              {[
                {
                  title: translations.checkSymptoms,
                  desc: translations.checkSymptomsDesc,
                  path: '/symptoms',
                  icon: HeartPulse,
                  borderClass: 'border-purple-100 hover:border-purple-300',
                  iconWrapperClass: 'bg-purple-50 text-purple-600',
                  arrowColor: 'text-purple-600',
                  shadowClass: 'hover:shadow-[0_12px_24px_-8px_rgba(147,51,234,0.15)]'
                },
                {
                  title: translations.myRecords,
                  desc: translations.myRecordsDesc,
                  path: '/profile',
                  icon: User,
                  borderClass: 'border-blue-100 hover:border-blue-300',
                  iconWrapperClass: 'bg-blue-50 text-blue-600',
                  arrowColor: 'text-blue-600',
                  shadowClass: 'hover:shadow-[0_12px_24px_-8px_rgba(37,99,235,0.15)]'
                },
                {
                  title: translations.womenPregnancy,
                  desc: translations.womenPregnancyDesc,
                  path: '/menstrual-health',
                  icon: Droplets,
                  borderClass: 'border-pink-100 hover:border-pink-300',
                  iconWrapperClass: 'bg-pink-50 text-pink-600',
                  arrowColor: 'text-pink-600',
                  shadowClass: 'hover:shadow-[0_12px_24px_-8px_rgba(219,39,119,0.15)]'
                },
                {
                  title: translations.govSchemes,
                  desc: translations.govSchemesDesc,
                  path: '/schemes',
                  icon: Landmark,
                  borderClass: 'border-emerald-100 hover:border-emerald-300',
                  iconWrapperClass: 'bg-emerald-50 text-emerald-600',
                  arrowColor: 'text-emerald-600',
                  shadowClass: 'hover:shadow-[0_12px_24px_-8px_rgba(16,185,129,0.15)]'
                }
              ].map((service) => (
                <motion.div
                  key={service.title}
                  variants={itemVariants}
                  whileHover={{ y: -4 }}
                  className={`bg-white border ${service.borderClass} rounded-2xl p-6 flex flex-col justify-between transition-all duration-300 shadow-sm cursor-pointer ${service.shadowClass}`}
                  onClick={() => navigate(service.path)}
                >
                  <div>
                    <div className={`w-12 h-12 rounded-2xl flex items-center justify-center shadow-inner ${service.iconWrapperClass} mb-4`}>
                      <service.icon className="w-6 h-6" />
                    </div>
                    <h4 className="text-base font-extrabold text-slate-800 tracking-tight">{service.title}</h4>
                    <p className="text-xs text-slate-500 font-bold leading-normal mt-2">{service.desc}</p>
                  </div>
                  
                  <div className="mt-6 flex justify-end">
                    <ChevronRight className={`w-5 h-5 ${service.arrowColor}`} />
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </section>

          {/* Row 3: Your Health Snapshot Row */}
          <section className="space-y-5">
            <h3 className="text-lg font-black text-slate-800 tracking-tight">
              {translations.healthSnapshot}
            </h3>

            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="bg-white border border-slate-200/80 rounded-3xl p-6 md:p-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 shadow-sm"
            >
              {/* Metric 1: Health Score */}
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shadow-inner shrink-0">
                  <HeartPulse className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{translations.healthScore}</p>
                  <p className="text-2xl font-black text-slate-800 mt-0.5">85%</p>
                  <p className="text-xs font-black text-emerald-600 mt-0.5">{translations.healthScoreStatus}</p>
                </div>
              </div>

              {/* Metric 2: Checkups Done */}
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shadow-inner shrink-0">
                  <CheckCircle2 className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{translations.checkupsDone}</p>
                  <p className="text-2xl font-black text-slate-800 mt-0.5">3</p>
                  <p className="text-xs font-bold text-slate-500 mt-0.5">{translations.checkupsDoneSub}</p>
                </div>
              </div>

              {/* Metric 3: Active Alerts */}
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-amber-50 text-amber-600 flex items-center justify-center shadow-inner shrink-0">
                  <Bell className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{translations.activeAlerts}</p>
                  <p className="text-2xl font-black text-slate-800 mt-0.5">2</p>
                  <p className="text-xs font-black text-rose-600 mt-0.5">{translations.activeAlertsSub}</p>
                </div>
              </div>

              {/* Metric 4: Last Checkup */}
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-purple-50 text-purple-600 flex items-center justify-center shadow-inner shrink-0">
                  <Calendar className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{translations.lastCheckup}</p>
                  <p className="text-2xl font-black text-slate-800 mt-0.5">{translations.daysAgo}</p>
                  <p className="text-xs font-bold text-slate-500 mt-0.5">{translations.lastCheckupDate}</p>
                </div>
              </div>

            </motion.div>
          </section>

          {/* Technical Proof Elements */}
          <section className="grid grid-cols-2 lg:grid-cols-4 gap-6 pt-8 border-t border-slate-200/80">
            {[
              { title: translations.proofTitle1, desc: translations.proofDesc1, icon: Globe, color: 'text-emerald-600', bg: 'bg-emerald-50' },
              { title: translations.proofTitle2, desc: translations.proofDesc2, icon: WifiOff, color: 'text-blue-600', bg: 'bg-blue-50' },
              { title: translations.proofTitle3, desc: translations.proofDesc3, icon: Shield, color: 'text-pink-600', bg: 'bg-pink-50' },
              { title: translations.proofTitle4, desc: translations.proofDesc4, icon: Zap, color: 'text-purple-600', bg: 'bg-purple-50' }
            ].map(item => (
              <div key={item.title} className="flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-4 p-3.5 sm:p-4 bg-white/60 border border-slate-200/80 rounded-2xl shadow-inner hover:bg-white transition-colors duration-200">
                <div className={`p-2.5 sm:p-3 rounded-xl sm:rounded-2xl ${item.bg} ${item.color} shadow-sm shrink-0`}>
                  <item.icon className="w-4 h-4 sm:w-5 sm:h-5" />
                </div>
                <div className="w-full">
                  <h5 className="text-[10px] sm:text-xs font-black text-slate-800 leading-tight uppercase tracking-wider">{item.title}</h5>
                  <p className="text-[9px] sm:text-[10px] font-bold text-slate-500 mt-1">{item.desc}</p>
                </div>
              </div>
            ))}
          </section>

        </main>
      </div>

      {/* Health Alert Popup Modal */}
      <AnimatePresence>
        {alertModalOpen && (
          <div className="fixed inset-0 z-[300] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              className="bg-white border border-amber-100 rounded-[2.5rem] shadow-2xl w-full max-w-lg overflow-hidden relative"
            >
              {/* Colored top header block */}
              <div className="bg-[#FFFBEB] border-b border-[#FEF3C7] px-8 py-6 flex items-center gap-4">
                <div className="w-12 h-12 bg-amber-100/80 border border-amber-200 rounded-2xl flex items-center justify-center shadow-inner text-[#D97706]">
                  <AlertTriangle className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-extrabold text-[#92400E]">{translations.alertModalTitle}</h3>
                  <span className="text-[10px] font-black text-[#B45309] uppercase tracking-widest block mt-0.5">{translations.alertLocation}</span>
                </div>
              </div>

              {/* Modal Body */}
              <div className="p-8 space-y-6">
                <div className="px-4 py-2 bg-rose-50 border border-rose-100 text-rose-700 text-xs font-black uppercase tracking-wider rounded-xl inline-flex items-center gap-2">
                  <span className="w-2.5 h-2.5 bg-rose-500 rounded-full animate-pulse" />
                  {translations.alertStatus}
                </div>

                <div className="space-y-4 text-slate-600">
                  <p className="text-sm font-extrabold text-slate-800 bg-amber-50/50 p-4 border border-amber-100 rounded-xl leading-relaxed">
                    {translations.alertDesc}
                  </p>

                  <div className="space-y-3 pt-2">
                    <div className="flex gap-3 text-xs leading-relaxed font-bold">
                      <div className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                      <p>{translations.alertPrecaution1}</p>
                    </div>
                    <div className="flex gap-3 text-xs leading-relaxed font-bold">
                      <div className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                      <p>{translations.alertPrecaution2}</p>
                    </div>
                    <div className="flex gap-3 text-xs leading-relaxed font-bold">
                      <div className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                      <p>{translations.alertPrecaution3}</p>
                    </div>
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-slate-100">
                  <button
                    onClick={() => {
                      setAlertModalOpen(false);
                      navigate('/ambulance');
                    }}
                    className="flex-1 py-3.5 bg-[#DC2626] hover:bg-[#B91C1C] text-white rounded-2xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 shadow-md transition-all active:scale-98"
                  >
                    <Phone className="w-4 h-4 fill-white" />
                    <span>{translations.callAsha}</span>
                  </button>
                  <button
                    onClick={() => setAlertModalOpen(false)}
                    className="flex-1 py-3.5 bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200 rounded-2xl font-black text-xs uppercase tracking-widest transition-all active:scale-98"
                  >
                    {translations.closeBtn}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
